default:
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - api_failure

stages:
  - lint
  - test
  - publish

.rust-info-script:                 &rust-info-script
  - rustup show
  - cargo --version
  - rustup +nightly show
  - cargo +nightly --version
  - cargo spellcheck --version
  - bash --version
  - sccache -s

.kubernetes-env:          &kubernetes-env
  image:                  "node:16.15"
  tags:
    - kubernetes-parity-build

.docker-env:                       &docker-env
  image:                           "paritytech/ci-linux:production"
  before_script:
    - *rust-info-script
    - ./scripts/ci/pre_cache.sh
    - sccache -s
  interruptible:                   true
  tags:
    - linux-docker

lint:
  stage:                  lint
  <<:                     *kubernetes-env
  script:
    - make ts-install
    - make ts-lint

check-format:
  stage:                  lint
  <<:                     *kubernetes-env
  script:
    - make ts-install
    - make ts-check-format

check-spelling:
  stage:                  lint
  <<:                     *kubernetes-env
  script:
    - make ts-install
    - make ts-check-spelling

# Test
test-rust-analyzer-wasm:
  stage:                  test
  <<:                     *docker-env
  script:
    - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - wasm-pack test --headless --chrome crates/rust_analyzer_wasm