apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  serviceAccountName: my-service-account
  containers:
  - name: my-container
    image: ink-server:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 4000 # Specify the port ink! playground actix-web backend listens on.
    env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ACTIX_HOST
          value: 0.0.0.0
        - name: ACTIX_PORT
          value: 4000
              
