apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-pod
  ports:
  - protocol: TCP
    port: 4000  #port which is accessible on local machine
    targetPort: 4000 #port the pod uses for communication
    nodePort: 30000
  type: NodePort

