apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ink-playground-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin # Replace with the appropriate cluster role
subjects:
  - kind: ServiceAccount
    name: my-service-account
    namespace: default # Replace with the appropriate namespace
