apiVersion: v1
kind: Service
metadata:
  name: ink-playground-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: ink-playground-app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
