apiVersion: v1
kind: Service
metadata:
  name: ink-playground-service
spec:
  selector:
    app: ink-playground-pod
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: NodePort
