name: Kubernetes

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3

      - name: Build docker
        run: make docker-buildkit
        env:
          DOCKER_USER_NAME: achimcc

      - name: Tag Docker image
        run: docker tag achimcc/ink-playground:latest ink-playground-kubernetes:latest

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Create ServiceAccount
        run: kubectl apply -f ${{github.workspace}}/kubernetes/serviceaccount.yaml

      - name: Apply ClusterRoleBinding
        run: kubectl apply -f ${{github.workspace}}/kubernetes/clusterrolebinding.yaml

      - name: Load ink-playground-kubernetes image
        run: minikube image load ink-playground-kubernetes:latest

      - name: Load Pod
        run: kubectl apply -f ${{github.workspace}}/kubernetes/pod.yaml
        env:
          ACTIX_HOST: 0.0.0.0
          ACTIX_PORT: 4000

      - name: Wait for 30s, allow pod to start
        uses: juliangruber/sleep-action@v1
        with:
          time: 30s

      - name: Expose webserver Port from pod
        run: kubectl apply -f ${{github.workspace}}/kubernetes/service.yaml

      - name: Try the cluster
        run: kubectl get pods -A

      - name: Get pod details
        run: kubectl get pod ink-playground-pod -o json

      - name: Install nmap
        run: sudo apt install nmap

      - name: Check open ports
        run: sudo nmap $(minikube ip)
