name: Kubernetes

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3

      - name: Build docker
        run: make docker-buildkit
        env:
          DOCKER_USER_NAME: achimcc

      - name: Tag Docker image
        run: docker tag achimcc/ink-playground:latest ink-playground-kubernetes:latest

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Create ServiceAccount
        run: kubectl apply -f ./kubernetes/serviceaccount.yaml

      - name: Apply ClusterRoleBinding
        run: kubectl apply -f ./kubernetes/clusterrolebinding.yaml

      - name: Load ink-playground-kubernetes image
        run: minikube image load ink-playground-kubernetes:latest

      - name: Load Pod
        run: kubectl apply -f ./kubernetes/pod.yaml

      - name: Try the cluster 
        run: kubectl get pods -A
